apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-openebs
  namespace: openebs-operator
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: openebses
  attachments:
    - apiVersion: dao.mayadata.io/v1alpha1
      resource: openebses
      updateStrategy:
        method: InPlace
    - apiVersion: apps/v1
      resource: daemonsets
      updateStrategy:
        method: InPlace
      labelSelector:
        matchExpressions:
          - {key: openebs-upgrade.dao.mayadata.io/managed, operator: Exists}
    - apiVersion: apps/v1
      resource: deployments
      updateStrategy:
        method: InPlace
      labelSelector:
        matchExpressions:
          - {key: openebs-upgrade.dao.mayadata.io/managed, operator: Exists}
    - apiVersion: apps/v1
      resource: statefulsets
      updateStrategy:
        method: InPlace
      labelSelector:
        matchExpressions:
          - {key: openebs-upgrade.dao.mayadata.io/managed, operator: Exists}
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: InPlace
      labelSelector:
        matchExpressions:
          - {key: openebs-upgrade.dao.mayadata.io/managed, operator: Exists}
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
      labelSelector:
        matchExpressions:
          - {key: openebs-upgrade.dao.mayadata.io/managed, operator: Exists}
    - apiVersion: rbac.authorization.k8s.io/v1beta1
      resource: clusterrolebindings
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-maya-operator
        - openebs-cstor-csi-snapshotter-binding
        - openebs-cstor-csi-provisioner-binding
        - openebs-cstor-csi-attacher-binding
        - openebs-cstor-csi-cluster-registrar-binding
        - openebs-cstor-csi-registrar-binding
    - apiVersion: rbac.authorization.k8s.io/v1beta1
      resource: clusterroles
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-maya-operator
        - openebs-cstor-csi-snapshotter-role
        - openebs-cstor-csi-provisioner-role
        - openebs-cstor-csi-attacher-role
        - openebs-cstor-csi-cluster-registrar-role
        - openebs-cstor-csi-registrar-role
    - apiVersion: rbac.authorization.k8s.io/v1
      resource: clusterrolebindings
      updateStrategy:
        method: InPlace
      nameSelector:
        - moac
    - apiVersion: rbac.authorization.k8s.io/v1
      resource: clusterroles
      updateStrategy:
        method: InPlace
      nameSelector:
        - moac
    - apiVersion: v1
      resource: serviceaccounts
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-maya-operator
        - openebs-cstor-csi-controller-sa
        - openebs-cstor-csi-node-sa
        - moac
    - apiVersion: apiextensions.k8s.io/v1beta1
      resource: customresourcedefinitions
      updateStrategy:
        method: InPlace
      nameSelector:
        - cstorpoolclusters.openebs.io
        - csinodeinfos.csi.storage.k8s.io
        - csivolumes.openebs.io
        - volumesnapshotclasses.snapshot.storage.k8s.io
        - volumesnapshotcontents.snapshot.storage.k8s.io
        - volumesnapshots.snapshot.storage.k8s.io
        - cstorvolumeattachments.cstor.openebs.io
        - cstorbackups.openebs.io
        - cstorcompletedbackups.openebs.io
        - cstorrestores.openebs.io
        - mayastorpools.openebs.io
    - apiVersion: apiextensions.k8s.io/v1
      resource: customresourcedefinitions
      updateStrategy:
        method: InPlace
      nameSelector:
        - cstorpoolclusters.cstor.openebs.io
        - cstorpoolinstances.cstor.openebs.io
        - cstorvolumes.cstor.openebs.io
        - cstorvolumeconfigs.cstor.openebs.io
        - cstorvolumepolicies.cstor.openebs.io
        - cstorvolumereplicas.cstor.openebs.io
        - cstorbackups.cstor.openebs.io
        - cstorcompletedbackups.cstor.openebs.io
        - cstorrestores.cstor.openebs.io
        - migrationtasks.openebs.io
    - apiVersion: storage.k8s.io/v1beta1
      resource: csidrivers
      updateStrategy:
        method: InPlace
      nameSelector:
        - cstor.csi.openebs.io
    - apiVersion: v1
      resource: namespaces
      updateStrategy:
        method: InPlace
      nameSelector:
        - mayastor
    - apiVersion: scheduling.k8s.io/v1
      resource: priorityclasses
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-csi-controller-critical
        - openebs-csi-node-critical
  hooks:
    sync:
      inline:
        funcName: sync/openebs

---

apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-adoptopenebs
  namespace: openebs-operator
spec:
  updateAny: true
  watch:
    apiVersion: dao.mayadata.io/v1alpha1
    resource: adoptopenebses
  attachments:
    - apiVersion: dao.mayadata.io/v1alpha1
      resource: adoptopenebses
    - apiVersion: dao.mayadata.io/v1alpha1
      resource: openebses
    - apiVersion: apps/v1
      resource: daemonsets
      updateStrategy:
        method: InPlace
    - apiVersion: apps/v1
      resource: deployments
      updateStrategy:
        method: InPlace
    - apiVersion: apps/v1
      resource: statefulsets
      updateStrategy:
        method: InPlace
    - apiVersion: v1
      resource: configmaps
      updateStrategy:
        method: InPlace
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
    - apiVersion: rbac.authorization.k8s.io/v1beta1
      resource: clusterrolebindings
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-maya-operator
        - openebs-cstor-csi-snapshotter-binding
        - openebs-cstor-csi-provisioner-binding
        - openebs-cstor-csi-attacher-binding
        - openebs-cstor-csi-cluster-registrar-binding
        - openebs-cstor-csi-registrar-binding
    - apiVersion: rbac.authorization.k8s.io/v1beta1
      resource: clusterroles
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-maya-operator
        - openebs-cstor-csi-snapshotter-role
        - openebs-cstor-csi-provisioner-role
        - openebs-cstor-csi-attacher-role
        - openebs-cstor-csi-cluster-registrar-role
        - openebs-cstor-csi-registrar-role
    - apiVersion: v1
      resource: serviceaccounts
      updateStrategy:
        method: InPlace
      nameSelector:
        - openebs-maya-operator
        - openebs-cstor-csi-controller-sa
        - openebs-cstor-csi-node-sa
    - apiVersion: apiextensions.k8s.io/v1beta1
      resource: customresourcedefinitions
      updateStrategy:
        method: InPlace
      nameSelector:
        - cstorpoolclusters.openebs.io
        - csinodeinfos.csi.storage.k8s.io
        - csivolumes.openebs.io
        - volumesnapshotclasses.snapshot.storage.k8s.io
        - volumesnapshotcontents.snapshot.storage.k8s.io
        - volumesnapshots.snapshot.storage.k8s.io
        - cstorvolumeattachments.cstor.openebs.io
    - apiVersion: apiextensions.k8s.io/v1
      resource: customresourcedefinitions
      updateStrategy:
        method: InPlace
      nameSelector:
        - cstorpoolclusters.cstor.openebs.io
        - cstorpoolinstances.cstor.openebs.io
        - cstorvolumes.cstor.openebs.io
        - cstorvolumeconfigs.cstor.openebs.io
        - cstorvolumepolicies.cstor.openebs.io
        - cstorvolumereplicas.cstor.openebs.io
        - cstorbackups.cstor.openebs.io
        - cstorcompletedbackups.cstor.openebs.io
        - cstorrestores.cstor.openebs.io
        - migrationtasks.openebs.io
  hooks:
    sync:
      inline:
        funcName: sync/adoptopenebs
